// Generated by CoffeeScript 1.3.3
(function() {
  var $, Activity, GITHUB, helpers, render, util,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  GITHUB = 'https://github.com';

  util = {
    truncate: function(s, l, append) {
      var o;
      if (l == null) {
        l = 50;
      }
      if (append == null) {
        append = "&hellip;";
      }
      o = s.slice(0, l);
      if (s.length > l) {
        o += append;
      }
      return o;
    },
    humanTime: function(date) {
      var days, del, hours, mins, now, secs;
      now = new Date();
      del = now - date;
      secs = del / 1000;
      if (secs < 5) {
        return "just now";
      }
      if (secs < 60) {
        return "" + (Math.floor(secs)) + "s ago";
      }
      mins = secs / 60;
      if (mins < 60) {
        return "" + (Math.floor(mins)) + "m ago";
      }
      hours = mins / 60;
      if (hours < 24) {
        return "" + (Math.floor(hours)) + "h ago";
      }
      days = hours / 24;
      return "" + (Math.floor(days)) + "d ago";
    },
    parseISO8601: function(string) {
      var d, date, offset, out, regexp, time;
      regexp = "([0-9]{4})(-([0-9]{2})(-([0-9]{2})" + "(T([0-9]{2}):([0-9]{2})(:([0-9]{2})(.([0-9]+))?)?" + "(Z|(([-+])([0-9]{2}):([0-9]{2})))?)?)?)?";
      d = string.match(new RegExp(regexp));
      offset = 0;
      date = new Date(d[1], 0, 1);
      if (d[3]) {
        date.setMonth(d[3] - 1);
      }
      if (d[5]) {
        date.setDate(d[5]);
      }
      if (d[7]) {
        date.setHours(d[7]);
      }
      if (d[8]) {
        date.setMinutes(d[8]);
      }
      if (d[10]) {
        date.setSeconds(d[10]);
      }
      if (d[12]) {
        date.setMilliseconds(Number("0." + d[12]) * 1000);
      }
      if (d[14]) {
        offset = (Number(d[16]) * 60) + Number(d[17]);
        offset *= (d[15] === "-" ? 1 : -1);
      }
      offset -= date.getTimezoneOffset();
      time = Number(date) + (offset * 60 * 1000);
      out = new Date();
      out.setTime(Number(time));
      return out;
    }
  };

  helpers = {
    github: {
      who: function(c) {
        return "<img src='#c.person.avatar'>\n<a href='#c.person.permalink'>" + c.person.display_name + "</a>";
      },
      repoUrl: function(c) {
        return '';
        return "" + GITHUB + "/" + c.repo.name;
      },
      repo: function(c) {
        return '';
        return "<a title='" + c.repo.name + " on GitHub' href='" + (helpers.github.repoUrl(c)) + "'>" + c.repo.name + "</a>";
      },
      titleForDefault: function(c) {
        return "did something";
      },
      titleForCommitCommentEvent: function(c) {
        return '';
        return "commented on\n<a href='" + c.payload.comment.html_url + "'>" + c.payload.comment.commit_id.slice(0, 7) + "</a>\non " + (helpers.github.repo(c));
      },
      titleForCreateEvent: function(c) {
        return '';
        return "created a " + c.payload.ref_type + " on " + (helpers.github.repo(c));
      },
      titleForDownloadEvent: function(c) {
        return '';
        return "created a new\n<a href='" + (helpers.github.repoUrl(c)) + "/downloads'>download</a>\non " + (helpers.github.repo(c));
      },
      titleForForkEvent: function(c) {
        return '';
        return "forked " + (helpers.github.repo(c));
      },
      titleForIssueCommentEvent: function(c) {
        return '';
        return "commented on issue\n<a href='" + c.payload.issue.html_url + "#issuecomment-" + c.payload.comment.id + "'>#" + c.payload.issue.number + "</a>\non " + (helpers.github.repo(c));
      },
      titleForIssuesEvent: function(c) {
        return '';
        return "" + c.payload.action + " issue <a href='" + c.payload.issue.html_url + "'>#" + c.payload.issue.number + "</a> on " + (helpers.github.repo(c));
      },
      titleForPullRequestEvent: function(c) {
        return '';
        return "" + c.payload.action + " pull request <a href='" + c.payload.pull_request.html_url + "'>#" + c.payload.pull_request.number + "</a> on " + (helpers.github.repo(c));
      },
      titleForPushEvent: function(c) {
        var branch;
        return '';
        branch = c.payload.ref.split('/')[2];
        if (branch) {
          return "pushed to <strong>" + branch + "</strong> on " + (helpers.github.repo(c));
        } else {
          return "pushed to " + (helpers.github.repo(c));
        }
      },
      titleForWatchEvent: function(c) {
        return '';
        return "" + c.payload.action + " watching " + (helpers.github.repo(c));
      },
      detailsForDefault: function(c) {
        return '';
        return "More " + c.type + " details here &hellip;";
      },
      detailsForCommitCommentEvent: function(c) {
        return '';
        return util.truncate(c.payload.comment.body);
      },
      detailsForCreateEvent: function(c) {
        var o;
        return '';
        o = [];
        if (c.payload.ref_type === "tag") {
          o.push("Tagged ");
        } else {
          o.push("Created ref ");
        }
        o.push("<a href='" + (helpers.github.repoUrl(c)) + "/tree/" + c.payload.ref + "'>" + c.payload.ref + "</a>");
        return o.join('');
      },
      detailsForDownloadEvent: function(c) {
        return '';
        return "" + (util.truncate(c.payload.download.description));
      },
      detailsForForkEvent: function(c) {
        return '';
        return "&rarr; <a href='" + c.payload.forkee.html_url + "'>" + c.payload.forkee.html_url + "</a>";
      },
      detailsForIssueCommentEvent: function(c) {
        return '';
        return util.truncate(c.payload.comment.body);
      },
      detailsForIssuesEvent: function(c) {
        return '';
        return "" + (util.truncate(c.payload.issue.title));
      },
      detailsForPullRequestEvent: function(c) {
        return '';
        return "" + (util.truncate(c.payload.pull_request.title));
      },
      detailsForPushEvent: function(c) {
        var commit, maxCommits, o, _i, _len, _ref;
        return '';
        maxCommits = 3;
        o = [];
        _ref = c.payload.commits.slice(0, maxCommits);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          commit = _ref[_i];
          o.push("" + (util.truncate(commit.message, 50, '')) + "<a href='" + (helpers.github.repoUrl(c)) + "/commit/" + commit.sha + "'>&hellip;</a>");
        }
        if (c.payload.commits.length > maxCommits) {
          o.push("and " + (c.payload.commits.length - maxCommits) + " more&hellip;");
        }
        return o.join("<br>");
      },
      detailsForWatchEvent: function(c) {
        return "";
      },
      title: function(ev) {
        var c, t;
        return '';
        c = ev.content;
        t = helpers.github["titleFor" + c.type] || helpers.github.titleForDefault;
        return "" + (helpers.github.who(c)) + " " + (t(c));
      },
      details: function(ev) {
        var c, d;
        return '';
        c = ev.content;
        d = helpers.github["detailsFor" + c.type] || helpers.github.detailsForDefault;
        return "" + (d(c));
      }
    },
    mailman: {
      who: function(ev) {
        return '';
        return ev.from.replace(/"([^"]+)"(.+)/, "$1");
      },
      whichList: function(ev) {
        return '';
        return ev.subject.replace(/\[([^\]]+)\](.+)/, "$1");
      },
      title: function(ev) {
        return '';
        return "<strong>" + (helpers.mailman.who(ev)) + "</strong>\n<a href=\"" + ev.url + "\">emailed</a>\n<strong>" + (helpers.mailman.whichList(ev)) + "</strong>";
      },
      details: function(ev) {
        var subj;
        return '';
        subj = ev.subject.replace(/\[([^\]]+)\]\s+(.+)/, "$2");
        return "" + (util.truncate(subj, 50, '')) + "<a href='" + ev.url + "'>&hellip;</a>";
      }
    },
    "default": {
      title: function(ev) {
        return "Default title";
      },
      details: function(ev) {
        return "Default details";
      }
    }
  };

  render = function(ev) {
    var date, details, title, _ref, _ref1, _ref2, _ref3;
    date = util.humanTime(util.parseISO8601(ev.timestamp));
    title = (_ref = (_ref1 = helpers[ev._activity_type]) != null ? _ref1.title : void 0) != null ? _ref : helpers["default"].title;
    details = (_ref2 = (_ref3 = helpers[ev._activity_type]) != null ? _ref3.details : void 0) != null ? _ref2 : helpers["default"].details;
    return "<div class='event'>\n  <p class='title'>\n    <span class='when'>" + date + "</span>\n    <span class='what'>" + (title(ev)) + "</span>\n  </p>\n  <p class='details'>" + (details(ev)) + "</p>\n</div>";
  };

  Activity = (function() {

    Activity.prototype.events = [];

    function Activity(element, options) {
      var self,
        _this = this;
      this.element = element;
      this.options = options;
      this.gotEvents = __bind(this.gotEvents, this);

      self = this;
      $(this.element).addClass('activity').addClass('loading');
      $.each(this.options.url, function(i, url) {
        return $.ajax({
          url: url,
          dataType: 'jsonp',
          success: _this.gotEvents,
          error: _this.error
        });
      });
    }

    Activity.prototype.gotEvents = function(jsonObject) {
      this.events = this.events.concat(jsonObject.data);
      this.events.sort(function(a, b) {
        if (a.timestamp > b.timestamp) {
          return -1;
        } else {
          return 1;
        }
      });
      window.events = this.events;
      $(this.element).removeClass('loading');
      return this.drawEvents();
    };

    Activity.prototype.error = function(e) {
      return console.log('error', e);
    };

    Activity.prototype.drawEvents = function() {
      var e, res, _i, _len, _ref, _results;
      this.element.empty();
      _ref = this.events;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        e = _ref[_i];
        res = render(e);
        _results.push($(res).appendTo(this.element));
      }
      return _results;
    };

    return Activity;

  })();

  jQuery.fn.activity = function(options) {
    if (!options['url']) {
      console.error("Activity plugin needs 'url' key!");
      return this;
    }
    new Activity(this, options);
    return this;
  };

}).call(this);
